//
// Generated file, do not edit! Created by nedtool 5.6 from inet/_extra/applications/codefagent/CoDefMsgs.msg.
//

#ifndef __INET_CODEFMSGS_M_H
#define __INET_CODEFMSGS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class CoDefRequestHeader;
class CoDefResponseHeader;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Enum generated from <tt>inet/_extra/applications/codefagent/CoDefMsgs.msg:21</tt> by nedtool.
 * <pre>
 * enum RequestType
 * {
 *     GET = 1;
 *     POST = 2;
 *     PUT = 3;
 *     DEL = 4;
 * }
 * </pre>
 */
enum RequestType {
    GET = 1,
    POST = 2,
    PUT = 3,
    DEL = 4
};

/**
 * Enum generated from <tt>inet/_extra/applications/codefagent/CoDefMsgs.msg:28</tt> by nedtool.
 * <pre>
 * enum ResponseType
 * {
 *     //Success 2.xx
 *     CREATED = 201;
 *     DELETED = 202;
 *     VALID = 203;
 *     CHANGED = 204;
 *     CONTENT = 205;
 *     ///Client Error 4.xx
 *     BAD_REQUEST = 400;
 *     UNAUTHORIZED = 401;
 *     BAD_OPTION = 402;
 *     FORBIDDEN = 403;
 *     NOT_FOUND = 404;
 *     METHOD_NOT_ALLOWED = 405;
 *     NOT_ACCEPTABLE = 406;
 *     CONFLICT = 409;
 *     PRECONDITION_FAILED = 412;
 *     REQUEST_ENTITY_TOO_LARGE = 413;
 *     UNSUPPORTED_CONTENT_FORMAT = 415;
 *     //Server Error 5.xx
 *     INTERNAL_SERVER_ERROR = 500;
 *     NOT_IMPLEMENTED = 501;
 *     BAD_GATEWAY = 502;
 *     SERVICE_UNAVAILABLE = 503;
 *     GATEWAY_TIMEOUT = 504;
 *     PROXYING_NOT_SUPPORTED = 505;
 * }
 * </pre>
 */
enum ResponseType {
    CREATED = 201,
    DELETED = 202,
    VALID = 203,
    CHANGED = 204,
    CONTENT = 205,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    BAD_OPTION = 402,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    METHOD_NOT_ALLOWED = 405,
    NOT_ACCEPTABLE = 406,
    CONFLICT = 409,
    PRECONDITION_FAILED = 412,
    REQUEST_ENTITY_TOO_LARGE = 413,
    UNSUPPORTED_CONTENT_FORMAT = 415,
    INTERNAL_SERVER_ERROR = 500,
    NOT_IMPLEMENTED = 501,
    BAD_GATEWAY = 502,
    SERVICE_UNAVAILABLE = 503,
    GATEWAY_TIMEOUT = 504,
    PROXYING_NOT_SUPPORTED = 505
};

/**
 * Class generated from <tt>inet/_extra/applications/codefagent/CoDefMsgs.msg:56</tt> by nedtool.
 * <pre>
 * class CoDefRequestHeader extends FieldsChunk
 * {
 *     RequestType header;
 *     string uriPath[];
 * }
 * </pre>
 */
class INET_API CoDefRequestHeader : public ::inet::FieldsChunk
{
  protected:
    inet::RequestType header = static_cast<inet::RequestType>(-1);
    omnetpp::opp_string *uriPath = nullptr;
    size_t uriPath_arraysize = 0;

  private:
    void copy(const CoDefRequestHeader& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CoDefRequestHeader&);

  public:
    CoDefRequestHeader();
    CoDefRequestHeader(const CoDefRequestHeader& other);
    virtual ~CoDefRequestHeader();
    CoDefRequestHeader& operator=(const CoDefRequestHeader& other);
    virtual CoDefRequestHeader *dup() const override {return new CoDefRequestHeader(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual inet::RequestType getHeader() const;
    virtual void setHeader(inet::RequestType header);
    virtual void setUriPathArraySize(size_t size);
    virtual size_t getUriPathArraySize() const;
    virtual const char * getUriPath(size_t k) const;
    virtual void setUriPath(size_t k, const char * uriPath);
    virtual void insertUriPath(const char * uriPath);
    virtual void insertUriPath(size_t k, const char * uriPath);
    virtual void eraseUriPath(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CoDefRequestHeader& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CoDefRequestHeader& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/_extra/applications/codefagent/CoDefMsgs.msg:61</tt> by nedtool.
 * <pre>
 * class CoDefResponseHeader extends FieldsChunk
 * {
 *     ResponseType header;
 *     string uriPath[];
 * }
 * </pre>
 */
class INET_API CoDefResponseHeader : public ::inet::FieldsChunk
{
  protected:
    inet::ResponseType header = static_cast<inet::ResponseType>(-1);
    omnetpp::opp_string *uriPath = nullptr;
    size_t uriPath_arraysize = 0;

  private:
    void copy(const CoDefResponseHeader& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CoDefResponseHeader&);

  public:
    CoDefResponseHeader();
    CoDefResponseHeader(const CoDefResponseHeader& other);
    virtual ~CoDefResponseHeader();
    CoDefResponseHeader& operator=(const CoDefResponseHeader& other);
    virtual CoDefResponseHeader *dup() const override {return new CoDefResponseHeader(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual inet::ResponseType getHeader() const;
    virtual void setHeader(inet::ResponseType header);
    virtual void setUriPathArraySize(size_t size);
    virtual size_t getUriPathArraySize() const;
    virtual const char * getUriPath(size_t k) const;
    virtual void setUriPath(size_t k, const char * uriPath);
    virtual void insertUriPath(const char * uriPath);
    virtual void insertUriPath(size_t k, const char * uriPath);
    virtual void eraseUriPath(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CoDefResponseHeader& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CoDefResponseHeader& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_CODEFMSGS_M_H

