//
// Generated file, do not edit! Created by nedtool 5.6 from inet/_extra/transportlayer/PortRange.msg.
//

#ifndef __PORTRANGE_M_H
#define __PORTRANGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif



struct PortRange;
/**
 * Enum generated from <tt>inet/_extra/transportlayer/PortRange.msg:16</tt> by nedtool.
 * <pre>
 * enum PortOp
 * {
 *     NO_OP = 0;
 *     LTE = 1; //<=
 *     GTE = 2; //>=
 *     EQ = 3; //==
 *     NEQ = 4; //!=
 * }
 * </pre>
 */
enum PortOp {
    NO_OP = 0,
    LTE = 1,
    GTE = 2,
    EQ = 3,
    NEQ = 4
};

/**
 * Struct generated from inet/_extra/transportlayer/PortRange.msg:24 by nedtool.
 */
struct INET_API PortRange
{
    PortRange();
    PortOp op;
    uint16_t lowerPort;
    uint16_t upperPort;
};

// helpers for local use
void INET_API __doPacking(omnetpp::cCommBuffer *b, const PortRange& a);
void INET_API __doUnpacking(omnetpp::cCommBuffer *b, PortRange& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PortRange& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PortRange& obj) { __doUnpacking(b, obj); }

#endif // ifndef __PORTRANGE_M_H

